// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var User$ReactTemplate = require("./User.bs.js");
var AppStyle$ReactTemplate = require("./AppStyle.bs.js");
var LinkShare$ReactTemplate = require("./LinkShare.bs.js");
var CurrentlyPlaying$ReactTemplate = require("./CurrentlyPlaying.bs.js");

var userIcon = require("./img/user.png");

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: AppStyle$ReactTemplate.app
                        }, ReasonReact.element(undefined, undefined, User$ReactTemplate.make(/* array */[])), React.createElement("h1", {
                              className: AppStyle$ReactTemplate.pageTitle
                            }, "Welcome to SpotDJ"), ReasonReact.element(undefined, undefined, LinkShare$ReactTemplate.make(/* array */[])), ReasonReact.element(undefined, undefined, CurrentlyPlaying$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Css = 0;

exports.Css = Css;
exports.userIcon = userIcon;
exports.component = component;
exports.make = make;
/* userIcon Not a pure module */
