// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LogIn$ReactTemplate = require("./LogIn.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var LinkShare$ReactTemplate = require("./LinkShare.bs.js");
var GetUsername$ReactTemplate = require("./GetUsername.bs.js");
var GetCurrentlyPlayingQuery$ReactTemplate = require("./GetCurrentlyPlayingQuery.bs.js");

var pageTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("pageTitle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              56
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                16
              ]),
          /* [] */0
        ]
      ]
    ]);

var pageSubTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("pageSubTitle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              32
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                64
              ]),
          /* :: */[
            Emotion.fontWeight(200),
            /* [] */0
          ]
        ]
      ]
    ]);

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              self[/* state */1][/* auth */1].isLoggedIn("spotify").then((function (loginStatus) {
                        console.log(loginStatus);
                        Curry._1(self[/* send */3], /* SetLogInStatus */[loginStatus]);
                        return Promise.resolve(/* () */0);
                      })).catch((function (err) {
                      return Promise.resolve((console.log(err), /* () */0));
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* isLoggedIn */0];
              return React.createElement("div", undefined, match ? React.createElement("div", undefined, ReasonReact.element(undefined, undefined, GetUsername$ReactTemplate.make(self[/* state */1][/* auth */1], (function (status) {
                                          return Curry._1(self[/* send */3], /* SetLogInStatus */[status]);
                                        }), /* array */[])), React.createElement("h1", {
                                    className: pageTitle
                                  }, "SpotDJ"), React.createElement("h2", {
                                    className: pageSubTitle
                                  }, "Share your Spotify music live"), ReasonReact.element(undefined, undefined, LinkShare$ReactTemplate.make(self[/* state */1][/* isPublic */2], (function (param) {
                                          return Curry._1(self[/* send */3], /* ToggleShareStatus */0);
                                        }), /* array */[])), ReasonReact.element(undefined, undefined, GetCurrentlyPlayingQuery$ReactTemplate.make(/* array */[]))) : ReasonReact.element(undefined, undefined, LogIn$ReactTemplate.make(self[/* state */1][/* auth */1], (function (status) {
                                      return Curry._1(self[/* send */3], /* SetLogInStatus */[status]);
                                    }), /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* isLoggedIn */false,
                      /* auth */Client$ReactTemplate.auth,
                      /* isPublic */true
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[
                            /* isLoggedIn */action[0],
                            /* auth */state[/* auth */1],
                            /* isPublic */state[/* isPublic */2]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* isLoggedIn */state[/* isLoggedIn */0],
                            /* auth */state[/* auth */1],
                            /* isPublic */!state[/* isPublic */2]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.pageTitle = pageTitle;
exports.pageSubTitle = pageSubTitle;
exports.component = component;
exports.make = make;
/* pageTitle Not a pure module */
