// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.textAlign(/* center */98248149),
        /* [] */0
      ]
    ]);

exports.app = app;
/* app Not a pure module */
