// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.textAlign(/* center */98248149),
        /* [] */0
      ]
    ]);

var userIcon = Emotion.css(undefined, /* :: */[
      Emotion.label("userIcon"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              25
            ]),
        /* [] */0
      ]
    ]);

function flexWrapper(justify) {
  return Emotion.css(undefined, /* :: */[
              Emotion.label("flexWrapper"),
              /* :: */[
                Emotion.display(/* flex */-1010954439),
                /* :: */[
                  Emotion.justifyContent(justify),
                  /* [] */0
                ]
              ]
            ]);
}

var flexWrapperRightAlign = Emotion.css(undefined, /* :: */[
      Emotion.label("flexWrapperRightAlign"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.alignItems(/* center */98248149),
          /* :: */[
            Emotion.justifyContent(/* flexEnd */924268066),
            /* [] */0
          ]
        ]
      ]
    ]);

var pageTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("pageTitle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              48
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                64
              ]),
          /* [] */0
        ]
      ]
    ]);

var pageSubTitle = Emotion.css(undefined, /* :: */[
      Emotion.label("pageSubTitle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              24
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                32
              ]),
          /* :: */[
            Emotion.fontWeight(300),
            /* [] */0
          ]
        ]
      ]
    ]);

var userAccountWrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("userAccountWrapper"),
      /* :: */[
        Emotion.padding4(/* `px */[
              25096,
              16
            ], /* `px */[
              25096,
              24
            ], /* `px */[
              25096,
              0
            ], /* `px */[
              25096,
              24
            ]),
        /* [] */0
      ]
    ]);

var linkSharing = Emotion.css(undefined, /* :: */[
      Emotion.label("linkSharing"),
      /* :: */[
        Emotion.marginBottom(/* `px */[
              25096,
              64
            ]),
        /* [] */0
      ]
    ]);

var shareLinkURL = Emotion.css(undefined, /* :: */[
      Emotion.label("shareLinkURL"),
      /* :: */[
        Emotion.border(/* `px */[
              25096,
              0
            ], /* none */-922086728, /* `hex */[
              5194459,
              "ffffff"
            ]),
        /* :: */[
          Emotion.borderBottom(/* `px */[
                25096,
                1
              ], /* solid */12956715, /* `hex */[
                5194459,
                "cfcfcf"
              ]),
          /* :: */[
            Emotion.padding2(/* `px */[
                  25096,
                  0
                ], /* `px */[
                  25096,
                  8
                ]),
            /* :: */[
              Emotion.width(/* `px */[
                    25096,
                    280
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var subInfo = Emotion.css(undefined, /* :: */[
      Emotion.label("subInfo"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              14
            ]),
        /* :: */[
          Emotion.color(/* `hex */[
                5194459,
                "a2a2a2"
              ]),
          /* :: */[
            Emotion.padding2(/* `px */[
                  25096,
                  0
                ], /* `px */[
                  25096,
                  8
                ]),
            /* :: */[
              Emotion.select("#stop-btn", /* :: */[
                    Emotion.color(/* `hex */[
                          5194459,
                          "ff4e4e"
                        ]),
                    /* :: */[
                      Emotion.margin2(/* `px */[
                            25096,
                            0
                          ], /* `px */[
                            25096,
                            16
                          ]),
                      /* :: */[
                        Emotion.textDecoration(/* underline */131142924),
                        /* :: */[
                          Emotion.select(":hover", /* :: */[
                                Emotion.cursor(/* pointer */-786317123),
                                /* :: */[
                                  Emotion.color(Emotion.Css[/* Color */11][/* red */121]),
                                  /* [] */0
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.app = app;
exports.userIcon = userIcon;
exports.flexWrapper = flexWrapper;
exports.flexWrapperRightAlign = flexWrapperRightAlign;
exports.pageTitle = pageTitle;
exports.pageSubTitle = pageSubTitle;
exports.userAccountWrapper = userAccountWrapper;
exports.linkSharing = linkSharing;
exports.shareLinkURL = shareLinkURL;
exports.subInfo = subInfo;
/* app Not a pure module */
