// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.textAlign(/* center */98248149),
        /* :: */[
          Emotion.backgroundColor(/* `hex */[
                5194459,
                "000000"
              ]),
          /* :: */[
            Emotion.minHeight(/* `vh */[
                  26418,
                  100
                ]),
            /* :: */[
              Emotion.minWidth(/* `vw */[
                    26433,
                    100
                  ]),
              /* :: */[
                Emotion.overflow(/* auto */-1065951377),
                /* :: */[
                  Emotion.color(/* `hex */[
                        5194459,
                        "ffffff"
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function flexWrapper(justify, align) {
  return Emotion.css(undefined, /* :: */[
              Emotion.label("flexWrapper"),
              /* :: */[
                Emotion.display(/* flex */-1010954439),
                /* :: */[
                  Emotion.justifyContent(justify),
                  /* :: */[
                    Emotion.alignItems(align),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

exports.app = app;
exports.flexWrapper = flexWrapper;
/* app Not a pure module */
