// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var BsReactstrap__Progress = require("@ahrefs/bs-reactstrap/src/BsReactstrap__Progress.bs.js");
var SharedCss$ReactTemplate = require("./SharedCss.bs.js");

var songImage = require("./img/now-playing-ex.png");

var audioWave = require("./img/audio-wave.png");

var like = require("./img/like.png");

var share = require("./img/share.png");

var playerWrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("playerWrapper"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              300
            ]),
        /* :: */[
          Emotion.position(/* relative */903134412),
          /* :: */[
            Emotion.margin3(/* `px */[
                  25096,
                  0
                ], /* auto */-1065951377, /* `px */[
                  25096,
                  64
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var songNameStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("songNameStyle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              24
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                0
              ]),
          /* :: */[
            Emotion.textAlign(/* left */-944764921),
            /* [] */0
          ]
        ]
      ]
    ]);

var artistNameStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("artistNameStyle"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              14
            ]),
        /* :: */[
          Emotion.marginBottom(/* `px */[
                25096,
                0
              ]),
          /* :: */[
            Emotion.textAlign(/* left */-944764921),
            /* [] */0
          ]
        ]
      ]
    ]);

var audioWaveStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("audioWaveStyle"),
      /* :: */[
        Emotion.height(/* `px */[
              25096,
              48
            ]),
        /* [] */0
      ]
    ]);

var actionBtnStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("actionBtnStyle"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              32
            ]),
        /* :: */[
          Emotion.border(/* `px */[
                25096,
                2
              ], /* solid */12956715, /* `hex */[
                5194459,
                "ffffff"
              ]),
          /* :: */[
            Emotion.borderRadius(/* `pct */[
                  5591841,
                  50
                ]),
            /* :: */[
              Emotion.padding(/* `px */[
                    25096,
                    4
                  ]),
              /* :: */[
                Emotion.margin(/* `px */[
                      25096,
                      4
                    ]),
                /* :: */[
                  Emotion.select(":hover", /* :: */[
                        Emotion.cursor(/* pointer */-786317123),
                        /* :: */[
                          Emotion.backgroundColor(/* `hex */[
                                5194459,
                                "525252"
                              ]),
                          /* [] */0
                        ]
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var progressBarStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("progressBarStyle"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              200
            ]),
        /* :: */[
          Emotion.height(/* `px */[
                25096,
                4
              ]),
          /* [] */0
        ]
      ]
    ]);

var albumImage = Emotion.css(undefined, /* :: */[
      Emotion.label("albumImage"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100
            ]),
        /* [] */0
      ]
    ]);

var component = ReasonReact.reducerComponent("User");

function make(songName, artistName, isPlaying, progressPct, imageUrl, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "current-playing"
                        }, React.createElement("div", {
                              className: playerWrapper
                            }, React.createElement("img", {
                                  className: albumImage,
                                  alt: "Album Image",
                                  src: imageUrl
                                }), React.createElement("div", {
                                  className: Cn.make(/* :: */[
                                        SharedCss$ReactTemplate.flexWrapper(/* spaceBetween */516682146, /* center */98248149),
                                        /* [] */0
                                      ])
                                }, React.createElement("div", undefined, React.createElement("h3", {
                                          className: songNameStyle
                                        }, songName), React.createElement("p", {
                                          className: artistNameStyle
                                        }, artistName)), React.createElement("img", {
                                      className: audioWaveStyle,
                                      alt: "Audio Wave",
                                      src: audioWave
                                    })), React.createElement("div", {
                                  className: Cn.make(/* :: */[
                                        SharedCss$ReactTemplate.flexWrapper(/* spaceBetween */516682146, /* center */98248149),
                                        /* [] */0
                                      ])
                                }, ReasonReact.element(undefined, undefined, BsReactstrap__Progress.make(undefined, undefined, undefined, Caml_option.some(progressPct), undefined, undefined, undefined, "success", progressBarStyle, undefined, undefined, /* array */[])), React.createElement("img", {
                                      className: actionBtnStyle,
                                      alt: "Share Icon",
                                      src: share
                                    }), React.createElement("img", {
                                      className: actionBtnStyle,
                                      alt: "Like Icon",
                                      src: like
                                    }))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* isDropdownOpen */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* isDropdownOpen */!state[/* isDropdownOpen */0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.songImage = songImage;
exports.audioWave = audioWave;
exports.like = like;
exports.share = share;
exports.playerWrapper = playerWrapper;
exports.songNameStyle = songNameStyle;
exports.artistNameStyle = artistNameStyle;
exports.audioWaveStyle = audioWaveStyle;
exports.actionBtnStyle = actionBtnStyle;
exports.progressBarStyle = progressBarStyle;
exports.albumImage = albumImage;
exports.component = component;
exports.make = make;
/* songImage Not a pure module */
