// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var AppStyle$ReactTemplate = require("./AppStyle.bs.js");

var songImage = require("./img/now-playing-ex.png");

var audioWave = require("./img/audio-wave.png");

var like = require("./img/like.png");

var share = require("./img/share.png");

var component = ReasonReact.reducerComponent("User");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "current-playing"
                        }, React.createElement("div", {
                              style: {
                                margin: "auto",
                                position: "relative",
                                width: "300px"
                              }
                            }, React.createElement("img", {
                                  style: {
                                    width: "100%"
                                  },
                                  alt: "Song Image",
                                  src: songImage
                                }), React.createElement("div", {
                                  className: AppStyle$ReactTemplate.songImageFilter
                                }), React.createElement("div", {
                                  className: Cn.make(/* :: */[
                                        AppStyle$ReactTemplate.flexWrapper(/* spaceAround */-485895757),
                                        /* :: */[
                                          AppStyle$ReactTemplate.songInfo,
                                          /* [] */0
                                        ]
                                      ])
                                }, React.createElement("img", {
                                      className: "audio-wave",
                                      alt: "Audio Wave",
                                      src: audioWave
                                    }), React.createElement("div", undefined, React.createElement("h3", {
                                          className: "song-name"
                                        }, "Song Name"), React.createElement("p", {
                                          className: "singer-name"
                                        }, "Author Name")), React.createElement("img", {
                                      className: "action-btn-circle",
                                      alt: "Like Icon",
                                      src: like
                                    }), React.createElement("img", {
                                      className: "action-btn-circle",
                                      alt: "Share Icon",
                                      src: share
                                    }))), React.createElement("p", undefined, "Played by userABC"));
            }),
          /* initialState */(function (param) {
              return /* record */[/* isDropdownOpen */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* isDropdownOpen */!state[/* isDropdownOpen */0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Css = 0;

exports.Css = Css;
exports.songImage = songImage;
exports.audioWave = audioWave;
exports.like = like;
exports.share = share;
exports.component = component;
exports.make = make;
/* songImage Not a pure module */
