// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var AppStyle$ReactTemplate = require("./AppStyle.bs.js");

var songImage = require("./img/now-playing-ex.png");

var audioWave = require("./img/audio-wave.png");

var like = require("./img/like.png");

var share = require("./img/share.png");

var songInfo = Emotion.css(undefined, /* :: */[
      Emotion.label("songInfo"),
      /* :: */[
        Emotion.alignItems(/* center */98248149),
        /* :: */[
          Emotion.width(/* `pct */[
                5591841,
                100
              ]),
          /* :: */[
            Emotion.padding(/* `px */[
                  25096,
                  16
                ]),
            /* :: */[
              Emotion.position(/* absolute */-1013592457),
              /* :: */[
                Emotion.bottom(/* `px */[
                      25096,
                      0
                    ]),
                /* :: */[
                  Emotion.color(/* `hex */[
                        5194459,
                        "ffffff"
                      ]),
                  /* :: */[
                    Emotion.select(".audio-wave", /* :: */[
                          Emotion.width(/* `px */[
                                25096,
                                48
                              ]),
                          /* [] */0
                        ]),
                    /* :: */[
                      Emotion.select(".action-btn-circle", /* :: */[
                            Emotion.width(/* `px */[
                                  25096,
                                  32
                                ]),
                            /* :: */[
                              Emotion.border(/* `px */[
                                    25096,
                                    2
                                  ], /* solid */12956715, /* `hex */[
                                    5194459,
                                    "ffffff"
                                  ]),
                              /* :: */[
                                Emotion.borderRadius(/* `pct */[
                                      5591841,
                                      50
                                    ]),
                                /* :: */[
                                  Emotion.padding(/* `px */[
                                        25096,
                                        4
                                      ]),
                                  /* :: */[
                                    Emotion.select(":hover", /* :: */[
                                          Emotion.cursor(/* pointer */-786317123),
                                          /* :: */[
                                            Emotion.backgroundColor(/* `hex */[
                                                  5194459,
                                                  "525252"
                                                ]),
                                            /* [] */0
                                          ]
                                        ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]),
                      /* :: */[
                        Emotion.select(".song-name", /* :: */[
                              Emotion.fontSize(/* `px */[
                                    25096,
                                    24
                                  ]),
                              /* :: */[
                                Emotion.marginBottom(/* `px */[
                                      25096,
                                      0
                                    ]),
                                /* [] */0
                              ]
                            ]),
                        /* :: */[
                          Emotion.select(".singer-name", /* :: */[
                                Emotion.fontSize(/* `px */[
                                      25096,
                                      14
                                    ]),
                                /* :: */[
                                  Emotion.marginBottom(/* `px */[
                                        25096,
                                        0
                                      ]),
                                  /* [] */0
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var songImageFilter = Emotion.css(undefined, /* :: */[
      Emotion.label("songImageFilter"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100
            ]),
        /* :: */[
          Emotion.height(/* `pct */[
                5591841,
                100
              ]),
          /* :: */[
            Emotion.position(/* absolute */-1013592457),
            /* :: */[
              Emotion.top(/* `px */[
                    25096,
                    0
                  ]),
              /* :: */[
                Emotion.backgroundImage(/* `linearGradient */[
                      616379637,
                      /* tuple */[
                        /* `deg */[
                          4995526,
                          -180
                        ],
                        /* :: */[
                          /* tuple */[
                            0,
                            /* `rgba */[
                              -878128972,
                              /* tuple */[
                                255,
                                255,
                                255,
                                0.00
                              ]
                            ]
                          ],
                          /* :: */[
                            /* tuple */[
                              85,
                              /* `hex */[
                                5194459,
                                "000000"
                              ]
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var component = ReasonReact.reducerComponent("User");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "current-playing"
                        }, React.createElement("div", {
                              style: {
                                margin: "auto",
                                position: "relative",
                                width: "300px"
                              }
                            }, React.createElement("img", {
                                  style: {
                                    width: "100%"
                                  },
                                  alt: "Song Image",
                                  src: songImage
                                }), React.createElement("div", {
                                  className: songImageFilter
                                }), React.createElement("div", {
                                  className: Cn.make(/* :: */[
                                        AppStyle$ReactTemplate.flexWrapper(/* spaceAround */-485895757, /* center */98248149),
                                        /* :: */[
                                          songInfo,
                                          /* [] */0
                                        ]
                                      ])
                                }, React.createElement("img", {
                                      className: "audio-wave",
                                      alt: "Audio Wave",
                                      src: audioWave
                                    }), React.createElement("div", undefined, React.createElement("h3", {
                                          className: "song-name"
                                        }, "Song Name"), React.createElement("p", {
                                          className: "singer-name"
                                        }, "Author Name")), React.createElement("img", {
                                      className: "action-btn-circle",
                                      alt: "Like Icon",
                                      src: like
                                    }), React.createElement("img", {
                                      className: "action-btn-circle",
                                      alt: "Share Icon",
                                      src: share
                                    }))), React.createElement("p", undefined, "Played by userABC"));
            }),
          /* initialState */(function (param) {
              return /* record */[/* isDropdownOpen */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* isDropdownOpen */!state[/* isDropdownOpen */0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Css = 0;

exports.Css = Css;
exports.songImage = songImage;
exports.audioWave = audioWave;
exports.like = like;
exports.share = share;
exports.songInfo = songInfo;
exports.songImageFilter = songImageFilter;
exports.component = component;
exports.make = make;
/* songImage Not a pure module */
