// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var User$ReactTemplate = require("./User.bs.js");

var ppx_printed_query = "query findUsername  {\nme  {\nspotify  {\nid  \ndisplayName  \n}\n\n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "me");
    var tmp;
    if (match$1 !== undefined) {
      var match$2 = Js_json.decodeObject(Caml_option.valFromOption(match$1));
      if (match$2 !== undefined) {
        var match$3 = Js_dict.get(Caml_option.valFromOption(match$2), "spotify");
        var tmp$1;
        if (match$3 !== undefined) {
          var value$1 = Caml_option.valFromOption(match$3);
          var match$4 = Js_json.decodeNull(value$1);
          if (match$4 !== undefined) {
            tmp$1 = undefined;
          } else {
            var match$5 = Js_json.decodeObject(value$1);
            var tmp$2;
            if (match$5 !== undefined) {
              var value$2 = Caml_option.valFromOption(match$5);
              var match$6 = Js_dict.get(value$2, "id");
              var tmp$3;
              if (match$6 !== undefined) {
                var value$3 = Caml_option.valFromOption(match$6);
                var match$7 = Js_json.decodeNull(value$3);
                if (match$7 !== undefined) {
                  tmp$3 = undefined;
                } else {
                  var match$8 = Js_json.decodeString(value$3);
                  tmp$3 = match$8 !== undefined ? match$8 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
                }
              } else {
                tmp$3 = undefined;
              }
              var match$9 = Js_dict.get(value$2, "displayName");
              var tmp$4;
              if (match$9 !== undefined) {
                var value$4 = Caml_option.valFromOption(match$9);
                var match$10 = Js_json.decodeNull(value$4);
                if (match$10 !== undefined) {
                  tmp$4 = undefined;
                } else {
                  var match$11 = Js_json.decodeString(value$4);
                  tmp$4 = match$11 !== undefined ? match$11 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$4));
                }
              } else {
                tmp$4 = undefined;
              }
              tmp$2 = {
                id: tmp$3,
                displayName: tmp$4
              };
            } else {
              tmp$2 = Js_exn.raiseError("graphql_ppx: Object is not a value");
            }
            tmp$1 = Caml_option.some(tmp$2);
          }
        } else {
          tmp$1 = undefined;
        }
        tmp = {
          spotify: tmp$1
        };
      } else {
        tmp = Js_exn.raiseError("graphql_ppx: Object is not a value");
      }
    } else {
      tmp = Js_exn.raiseError("graphql_ppx: Field me on type Query is missing");
    }
    return {
            me: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var GetUsername = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var GetUserNameQuery = ReasonApollo.CreateQuery([
      ppx_printed_query,
      parse
    ]);

var component = ReasonReact.statelessComponent("GetUsername");

function make$1(auth, setLogInStatus, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Curry.app(GetUserNameQuery[/* make */3], [
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              (function (param) {
                                  var result = param[/* result */0];
                                  if (typeof result === "number") {
                                    return React.createElement("div", undefined, "Loading");
                                  } else if (result.tag) {
                                    var match = result[0].me.spotify;
                                    if (match !== undefined) {
                                      var match$1 = Caml_option.valFromOption(match).displayName;
                                      if (match$1 !== undefined) {
                                        var name = match$1;
                                        return ReasonReact.element(name, undefined, User$ReactTemplate.make(auth, setLogInStatus, name, /* array */[]));
                                      } else {
                                        return ReasonReact.element("", undefined, User$ReactTemplate.make(auth, setLogInStatus, "", /* array */[]));
                                      }
                                    } else {
                                      return ReasonReact.element("", undefined, User$ReactTemplate.make(auth, setLogInStatus, "", /* array */[]));
                                    }
                                  } else {
                                    return React.createElement("div", undefined, result[0].message);
                                  }
                                })
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.GetUsername = GetUsername;
exports.GetUserNameQuery = GetUserNameQuery;
exports.component = component;
exports.make = make$1;
/* GetUserNameQuery Not a pure module */
