// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var BsReactstrap__Button = require("@ahrefs/bs-reactstrap/src/BsReactstrap__Button.bs.js");

var component = ReasonReact.statelessComponent("Login");

function handleLogIn(auth, setLogInStatus) {
  console.log("Clicked Login!!");
  auth.login("gmail").then((function (param) {
              return auth.isLoggedIn("gmail");
            })).then((function (loginStatus) {
            console.log(loginStatus);
            Curry._1(setLogInStatus, loginStatus);
            return Promise.resolve(/* () */0);
          })).catch((function (err) {
          return Promise.resolve((console.log(err), /* () */0));
        }));
  return /* () */0;
}

function make(auth, setLogInStatus, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, BsReactstrap__Button.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                    return handleLogIn(auth, setLogInStatus);
                                  }), undefined, undefined, undefined, /* array */["Log In"])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.handleLogIn = handleLogIn;
exports.make = make;
/* component Not a pure module */
