// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var appId = "bafd4254-c229-48c2-8c53-44a01477a43e";

function authToken(auth) {
  var match = auth.authHeaders().Authentication;
  if (match !== undefined) {
    return match.replace("Bearer ", "");
  }
  
}

var config = {
  appId: appId
};

exports.appId = appId;
exports.authToken = authToken;
exports.config = config;
/* No side effect */
