// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

function flexWrapper(justify, align) {
  return Emotion.css(undefined, /* :: */[
              Emotion.label("flexWrapper"),
              /* :: */[
                Emotion.display(/* flex */-1010954439),
                /* :: */[
                  Emotion.justifyContent(justify),
                  /* :: */[
                    Emotion.alignItems(align),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

exports.flexWrapper = flexWrapper;
/* Emotion Not a pure module */
