// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var AppStyle$ReactTemplate = require("./AppStyle.bs.js");
var BsReactstrap__Dropdown = require("@ahrefs/bs-reactstrap/src/BsReactstrap__Dropdown.bs.js");
var BsReactstrap__DropdownItem = require("@ahrefs/bs-reactstrap/src/BsReactstrap__DropdownItem.bs.js");
var BsReactstrap__DropdownMenu = require("@ahrefs/bs-reactstrap/src/BsReactstrap__DropdownMenu.bs.js");
var BsReactstrap__DropdownToggle = require("@ahrefs/bs-reactstrap/src/BsReactstrap__DropdownToggle.bs.js");

var userIcon = require("./img/user.png");

var userAccountWrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("userAccountWrapper"),
      /* :: */[
        Emotion.padding4(/* `px */[
              25096,
              16
            ], /* `px */[
              25096,
              0
            ], /* `px */[
              25096,
              0
            ], /* `px */[
              25096,
              24
            ]),
        /* :: */[
          Emotion.marginRight(/* `px */[
                25096,
                48
              ]),
          /* [] */0
        ]
      ]
    ]);

var component = ReasonReact.reducerComponent("User");

function make(auth, setLogInStatus, userName, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("header", {
                          className: AppStyle$ReactTemplate.flexWrapper(/* flexEnd */924268066, /* center */98248149)
                        }, React.createElement("div", {
                              style: {
                                width: "100px"
                              }
                            }, ReasonReact.element(undefined, undefined, BsReactstrap__Dropdown.make(undefined, undefined, undefined, undefined, self[/* state */1][/* isDropdownOpen */0], undefined, undefined, undefined, undefined, undefined, (function (param) {
                                        return Curry._1(self[/* send */3], /* Toggle */1);
                                      }), undefined, undefined, undefined, /* array */[
                                      ReasonReact.element(undefined, undefined, BsReactstrap__DropdownToggle.make(true, undefined, Cn.make(/* :: */[
                                                    AppStyle$ReactTemplate.flexWrapper(/* flexEnd */924268066, /* center */98248149),
                                                    /* :: */[
                                                      userAccountWrapper,
                                                      /* [] */0
                                                    ]
                                                  ]), undefined, undefined, undefined, undefined, undefined, "div", undefined, /* array */[
                                                React.createElement("img", {
                                                      className: AppStyle$ReactTemplate.userIcon,
                                                      alt: "user icon",
                                                      src: userIcon
                                                    }),
                                                React.createElement("p", {
                                                      style: {
                                                        margin: "0px",
                                                        flex: "0 0 auto"
                                                      }
                                                    }, userName)
                                              ])),
                                      ReasonReact.element(undefined, undefined, BsReactstrap__DropdownMenu.make(undefined, true, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, BsReactstrap__DropdownItem.make(undefined, undefined, undefined, undefined, undefined, (function (param) {
                                                            return Curry._1(self[/* send */3], /* HandleLogOut */0);
                                                          }), undefined, undefined, undefined, /* array */["Sign Out"]))]))
                                    ]))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* isDropdownOpen */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* isDropdownOpen */!state[/* isDropdownOpen */0]]]);
              } else {
                console.log("Clicked LogOut!!");
                return /* SideEffects */Block.__(1, [(function (_state) {
                              auth.logout("spotify").then((function (param) {
                                          return auth.isLoggedIn("spotify");
                                        })).then((function (loginStatus) {
                                        console.log(loginStatus);
                                        Curry._1(setLogInStatus, loginStatus);
                                        return Promise.resolve(/* () */0);
                                      })).catch((function (err) {
                                      return Promise.resolve((console.log(err), /* () */0));
                                    }));
                              return /* () */0;
                            })]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Css = 0;

exports.Css = Css;
exports.userIcon = userIcon;
exports.userAccountWrapper = userAccountWrapper;
exports.component = component;
exports.make = make;
/* userIcon Not a pure module */
